Repository ReagentX/imessage-exporter, pull requests merged in 2025-05, with the labels that each got.

#516 Bump supported versions
  README.md
Labels: documentation

#517 Coastal Lotus Hotfix 2
  README.md
  imessage-database/src/message_types/variants.rs
  imessage-database/src/tables/messages/message.rs
  imessage-database/src/tables/messages/tests/announcement.rs
  imessage-exporter/src/app/compatibility/converters/audio.rs
  imessage-exporter/src/exporters/html.rs
  imessage-exporter/src/exporters/txt.rs
Labels: release

#518 Feat/cs/refactor validation logic
  imessage-database/src/tables/messages/message.rs
  imessage-exporter/src/app/mod.rs
  imessage-exporter/src/app/options.rs
  imessage-exporter/src/app/progress.rs
Labels: crate: cli, enhancement

#529 Add message permalinks in HTML export
  imessage-exporter/src/exporters/html.rs
Labels: crate: cli, exporter, html, enhancement

#527 Feat/cs/support encrypted backups
  Cargo.lock
  README.md
  build.sh
  docs/faq.md
  docs/features.md
  imessage-database/Cargo.toml
  imessage-database/src/tables/attachment.rs
  imessage-database/src/tables/messages/message.rs
  imessage-database/src/tables/table.rs
  imessage-database/src/util/platform.rs
  imessage-exporter/Cargo.toml
  imessage-exporter/README.md
  imessage-exporter/src/app/compatibility/attachment_manager.rs
  imessage-exporter/src/app/compatibility/backup.rs
  imessage-exporter/src/app/compatibility/mod.rs
  imessage-exporter/src/app/error.rs
  imessage-exporter/src/app/options.rs
  imessage-exporter/src/app/runtime.rs
  imessage-exporter/src/app/sanitizers.rs
  imessage-exporter/src/exporters/html.rs
  imessage-exporter/src/exporters/txt.rs
Labels: crate: database, crate: cli, new feature, enhancement, compatibility

#537 Feat/cs/fix docs
  docs/features.md
  imessage-database/src/message_types/edited.rs
Labels: documentation

#538 Feat/cs/docs fixes
  docs/faq.md
  docs/features.md
Labels: documentation
